plugins {
    id 'com.android.application'
}
android {
    namespace 'com.sensisgoodff.sensor'
    compileSdk 34
    defaultConfig {
        applicationId "com.sensisgoodff.sensor"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
        debug {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies {
    implementation 'androidx.core:core:1.10.1'
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
    compileOnly 'dev.rikka.hidden:stub:4.3.2'
}
